#!/usr/bin/awk -f

BEGIN {
	FS = ""
}

{
	prop1 = prop2 = 0;
	for (i = 1; i < NF - 1; i++) {
		if (!prop1 && substr($0, i + 2) ~ $i $(i + 1))
			prop1 = 1
		if (!prop2 && $i == $(i + 2))
			prop2 = 1
		if (prop1 && prop2) {
			n++
			next
		}
	}
}

END {
	print n
}
