#!/usr/bin/awk -f

BEGIN          { FS = "[ ,]+" }
$2 == "on"     { for (x = $3; x <= $6; x++) for (y = $4; y <= $7; y++) light[x, y] = 1 ; next }
$2 == "off"    { for (x = $3; x <= $6; x++) for (y = $4; y <= $7; y++) light[x, y] = 0 ; next }
$1 == "toggle" { for (x = $2; x <= $5; x++) for (y = $3; y <= $6; y++) light[x, y] = !light[x, y] ; next }
END            { for (l in light) if (light[l]) n++; print n }
