#!/usr/bin/awk -f

function countmatch(s, r,   beg, ret) {
	beg = 1
	while ((beg = match(s, r)) > 0) {
		ret++
		s = substr(s, beg + 1)
	}
	return ret
}

/=>/ {
	atom[$1] = atom[$1] (atom[$1] ? " " : "") $3
}

NF == 1 {
	mol = $1
}

END {
	for (r in atom) {
		n = split(atom[r], a)
		for (i = 1; i <= n; i++) {
			m = countmatch(mol, r)
			for (j = 1; j <= m; j++) {
				s = gensub(r, a[i], j, mol)
				mols[s] = 1
			}
		}
	}
	for (m in mols) {
		count++
	}
	print count
}
