#!/usr/bin/awk -f

function lookandsay(str,  s, i, j, a, n) {
	i = 1;
	n = split(str, a, "")
	while (i <= n) {
		for (j = i + 1; a[i] == a[j]; j++)
			;
		s = s (j - i) a[i]
		i = j
	}
	return s
}

{
	s = $0
	for (i = 1; i <= 50; i++)
		s = lookandsay(s)
	print length(s)
}
