#!/usr/bin/awk -f

function check(a, b) {
	if (a == "cats" || a == "trees")
		return mfcsam[a] < b
	else if (a == "pomeranians" || a == "goldfish")
		return mfcsam[a] > b
	else
		return mfcsam[a] == b
}

BEGIN {
	FS = "[ :,]+"
	mfcsam["children"] = 3;
	mfcsam["cats"] = 7;
	mfcsam["samoyeds"] = 2;
	mfcsam["pomeranians"] = 3;
	mfcsam["akitas"] = 0;
	mfcsam["vizslas"] = 0;
	mfcsam["goldfish"] = 5;
	mfcsam["trees"] = 3;
	mfcsam["cars"] = 2;
	mfcsam["perfumes"] = 1;
}

{
	if (check($3, $4) && check($5, $6) && check($7, $8))
		print $2
}
