#!/usr/bin/awk -f

{
	speed[NR] = $4
	cycle[NR] = $14 + $7
	fly[NR] = $7
}

END {
	for (j = 1; j <= 2503; j++) {
		for (i = 1; i <= NR; i++) {
			if (((j - 1) % cycle[i]) + 1 <= fly[i]) {
				distance[i] += speed[i]
				if (d < distance[i]) {
					d = distance[i]
				}
			}
		}
		for (i = 1; i <= NR; i++) {
			if (distance[i] == d) {
				point[i]++
				if (max < point[i]) {
					max = point[i]
				}
			}
		}
	}
	print max
}
