#!/usr/bin/awk -f

function decode(a, n, id,    i, s) {
	for (i = 1; i <= n; i++) {
		if (a[i] == " ")
			s = s " "
		else
			s = s sprintf("%c", ntoa[(aton[a[i]] + id) % 26])
	}
	return s
}

function valid(name, chsum, i, a, s, m1, m2, m3, m4, m5, s1, s2, s3, s4, s5) {
	chsum = $(NF - 1)
	id = $(NF - 2)
	for (i = 1; i <= NF - 3; i++)
		name = name (i == 1 ? "" : " ") $i
	n = split(name, a, "")
	for (i = 1; i <= n; i++) {
		if (a[i] != " ")
			s[a[i]]++
	}
	for (i = 0; i < 26; i++) {
		l = sprintf("%c", 97 + i)
		if (!s[l])
			continue
		if (s[l] > m1) {
			m5 = m4;        s5 = s4;
			m4 = m3;        s4 = s3;
			m3 = m2;        s3 = s2;
			m2 = m1;        s2 = s1;
			m1 = s[l];      s1 = l;
		} else if (s[l] > m2) {
			m5 = m4;        s5 = s4;
			m4 = m3;        s4 = s3;
			m3 = m2;        s3 = s2;
			m2 = s[l];      s2 = l;
		} else if (s[l] > m3) {
			m5 = m4;        s5 = s4;
			m4 = m3;        s4 = s3;
			m3 = s[l];      s3 = l;
		} else if (s[l] > m4) {
			m5 = m4;        s5 = s4;
			m4 = s[l];      s4 = l;
		} else if (s[l] > m5) {
			m5 = s[l];      s5 = l;
		}
	}
	return (s1 s2 s3 s4 s5 == chsum && decode(a, n, id) == storageroom)
}

BEGIN {
	FS = "[-\\[\\]]"
	for (i = 97; i <= 122; i++) {
		a = sprintf("%c", i)
		n = i - 96
		aton[a] = n
		ntoa[n] = a
	}
	ntoa[0] = "z"
	storageroom = "northpole object storage"
}

valid() {
	print $(NF - 2)
}
