#!/usr/bin/awk -f

NR % 3 == 1 {
	a1 = $1
	a2 = $2
	a3 = $3
}

NR % 3 == 2 {
	b1 = $1
	b2 = $2
	b3 = $3
}

NR % 3 == 0 {
	if (a1 + b1 > $1 && $1 + b1 > a1 && $1 + a1 > b1)
		n++
	if (a2 + b2 > $2 && $2 + b2 > a2 && $2 + a2 > b2)
		n++
	if (a3 + b3 > $3 && $3 + b3 > a3 && $3 + a3 > b3)
		n++
}
	
END {
	print n + 0
}
