#!/usr/bin/awk -f

function aba(s, j,    a, n, i) {
	n = split(s, a, "")
	for (i = j; i <= n - 2; i++) {
		if (a[i] != a[i+1] && a[i] == a[i+2]) {
			bab = a[i] a[i+1] a[i+2]
			return i + 1
		}
	}
	return 0
}

function valid(    i, j, n, b, a) {
	for (i = 1; i <= NF; i += 2) {
		j = 1
		while ((n = aba($i, n))) {
			a = substr(bab, 1, 1)
			b = substr(bab, 2, 1)
			bab = b a b
			for (j = 2; j <= NF; j += 2) {
				if ($j ~ bab) {
					return 1
				}
			}
		}
	}
	return 0
}

BEGIN   { FS = "[\\[\\]]" }
valid() { n++ }
END     { print n + 0 }
