#!/usr/bin/awk -f

function abs(n) {
	return (n < 0) ? -n : n
}

function step(c) {
	if (c == "U" && abs(row - 1) <= 1)
		row--
	else if (c == "D" && abs(row + 1) <= 1)
		row++
	else if (c == "L" && abs(col - 1) <= 1)
		col--
	else if (c == "R" && abs(col + 1) <= 1)
		col++
}

BEGIN {
	FS = ""
	a[-1, -1] = 1
	a[-1, 0] = 2
	a[-1, 1] = 3
	a[0, -1] = 4
	a[0, 0] = 5
	a[0, 1] = 6
	a[1, -1] = 7
	a[1, 0] = 8
	a[1, 1] = 9
}

{
	for (i = 1; i <= NF; i++)
		step($i)
	printf "%d", a[row, col]
}
