#!/usr/bin/awk -f

BEGIN {
	FS = ""
}

{
	n = 0
	for (i = 1; i <= NF; i++) {
		let = ""
		rep = ""
		if ($i == "(") {
			i++
			while ($i ~ /[0-9]/)
				let = let $(i++)
			i++
			while ($i ~ /[0-9]/)
				rep = rep $(i++)
			i += let
			n += let * rep
		} else {
			n++
		}
	}
	print n
}
