#!/usr/bin/awk -f

function abba(s,    a, n, i) {
	n = split(s, a, "")
	for (i = 1; i <= n - 3; i++)
		if (a[i] != a[i+1] && a[i] == a[i+3] && a[i+1] == a[i+2])
			return 1
	return 0
}

function valid(    i, t) {
	t = 0
	for (i = 1; i <= NF; i++) {
		if (!t && (i % 2) && abba($i)) {
			t = 1
		} else if (!(i % 2) && abba($i)) {
			return 0
		}
	}
	return t
}

BEGIN   { FS = "[\\[\\]]" }
valid() { n++ }
END     { print n + 0 }
