#!/usr/bin/awk -f

function btod(    i, d) {
	for (i = 1; i <= NF; i++)
		d = d * 2 + ($i ~ /[BR]/ ? 1 : 0)
	return d
}

function getseat(    i) {
	for (i in seat)
		if (seat[i + 2] && !seat[i + 1])
			return i + 1
}

BEGIN { FS = "" }
      { seat[btod()] = 1 }
END   { print getseat() }
