#!/usr/bin/awk -f

BEGIN { FS = "[- :]+" }
      { b = $2 - $1
        matcha = $4 ~ "^.{" ($1 - 1) "}" $3 ".{" ($2 - $1 - 1) "}[^" $3 "]"
        matchb = $4 ~ "^.{" ($1 - 1) "}[^" $3 "].{" ($2 - $1 - 1) "}" $3
        if ((matcha || matchb) && !(matcha && matchb)) n++
      }
END   { print n }
