#!/usr/bin/awk -f

function count(a, b, j) {
	for (i = 1; i <= NF; i++) {
		split($i, a, "")
		for (j in a) {
			if (!b[a[j]]) {
				b[a[j]] = ++n
			}
		}
	}
}

BEGIN { RS = "" }
      { count() }
END   { print n }
