#!/usr/bin/awk -f

function genregexpa(a, b, letter,  regexp, i) {
	regexp = "^"
	for (i = 1; i < a; i++)
		regexp = regexp "."
	regexp = regexp letter
	for (i = 1; i < b; i++)
		regexp = regexp "."
	return regexp "[^" letter "].*$"
}

function genregexpb(a, b, letter,  regexp, i) {
	regexp = "^"
	for (i = 1; i < a; i++)
		regexp = regexp "."
	regexp = regexp "[^" letter "]"
	for (i = 1; i < b; i++)
		regexp = regexp "."
	return regexp letter ".*$"
}

BEGIN { FS = "[- :]+" }
      { b = $2 - $1
        matcha = $4 ~ genregexpa($1, b, $3)
        matchb = $4 ~ genregexpb($1, b, $3)
        if ((matcha || matchb) && !(matcha && matchb)) n++
      }
END   { print n }
