#!/usr/bin/awk -f

function btod(    i, d) {
	for (i = 1; i <= NF; i++)
		d = d * 2 + ($i ~ /[BR]/ ? 1 : 0)
	return d
}

BEGIN { FS = "" }
      { if ((d = btod()) > max) max = d }
END   { print max }
