#!/usr/bin/awk -f

function btod(b,    a, n, d, p) {
	n = split(b, a, "")
	p = 1
	for (i = 1; i <= n; i++) {
		if (a[n - i + 1] + 0) {
			d += p
		}
		p *= 2
	}
	return d
}

BEGIN {
	FS = ""
	max = ""
}

{
	b = ""
	for (i = 1; i <= NF; i++)
		b = b ($i ~ /[BR]/ ? "1" : "0")
	if (b > max)
		max = b
}

END {
	print btod(max)
}
