#!/usr/bin/awk -f

function btod(b,    a, n, d, p) {
	n = split(b, a, "")
	p = 1
	for (i = 1; i <= n; i++) {
		if (a[n - i + 1] + 0) {
			d += p
		}
		p *= 2
	}
	return d
}

BEGIN {
	FS = ""
}

{
	s = ""
	for (i = 1; i <= NF; i++)
		s = s ($i ~ /[BR]/ ? "1" : "0")
	seat[btod(s)] = 1
}

END {
	for (i in seat) {
		for (j in seat) {
			if (i == j + 2 && !seat[j + 1]) {
				print j + 1
				exit
			}
		}
	}
}
