#!/usr/bin/awk -f

function narrow(a, b, n,    c, d, i) {
	if (length(a) > 1) {
		for (i in a) {
			$0 = i
			c[$n]++
		}
		if (b)
			d = c[1] >= length(a) / 2
		else
			d = c[0] <= length(a) / 2
		for (i in a) {
			$0 = i
			if ($n == (d ? !b : b)) {
				delete a[i]
			}
		}
	}
}

BEGIN { FS = "" }
      { co2[$0] = oxygen[$0] = 1 }
END   {
	for (i = 1; (length(oxygen) + length(co2)) > 2; i++) {
		narrow(oxygen, 1, i)
		narrow(co2, 0, i)
	}
	for (value in oxygen) split(value, v1, "")
	for (value in co2)    split(value, v2, "")
	for (i = 1; i <= NF; i++) {
		m *= 2; n *= 2;
		if (v1[i]) m++
		if (v2[i]) n++
	}
	print n * m
}
