#!/usr/bin/awk -f

function min(a, b) {
	return a < b ? a : b
}

function max(a, b) {
	return a > b ? a : b
}

BEGIN {
	FS = ",| -> "
}

$1 == $3 {
	m = max($2, $4)
	for (i = min($2, $4); i <= m; i++) {
		if (++floor[$1, i] == 2) {
			n++
		}
	}
}

$2 == $4 {
	m = max($1, $3)
	for (i = min($1, $3); i <= m; i++) {
		if (++floor[i, $2] == 2) {
			n++
		}
	}
}

END {
	print n
}
