#!/usr/bin/awk -f

BEGIN { FS = "" }
      { co2[$0] = oxygen[$0] = 1 }
END   {
	for (i = 1; (length(oxygen) * length(co2)) > 1; i++) {
		delete coxygen
		delete cco2
		if (length(oxygen) > 1) {
			for (value in oxygen) {
				$0 = value
				coxygen[$i]++
			}
			c = coxygen[1] >= length(oxygen) / 2
			for (value in oxygen) {
				$0 = value
				if ($i == (c ? 0 : 1)) {
					delete oxygen[value]
				}
			}
		}
		if (length(co2) > 1) {
			for (value in co2) {
				$0 = value
				cco2[$i]++
			}
			c = cco2[0] <= length(co2) / 2
			for (value in co2) {
				$0 = value
				if ($i == (c ? 1 : 0)) {
					delete co2[value]
				}
			}
		}
	}
	for (value in oxygen) split(value, v1, "")
	for (value in co2)    split(value, v2, "")
	for (i = 1; i <= NF; i++) {
		m *= 2; n *= 2;
		if (v1[i]) m++
		if (v2[i]) n++
	}
	print n * m
}
