#!/usr/bin/awk -f

function visit(node,    i) {
	if (!visited[node] && node == "end")
		nways++
	if (visited[node] && node ~ /[a-z]/)
		return
	visited[node] = 1
	for (i = 1; i <= nsuccs[node]; i++)
		visit(succs[node, i])
	visited[node] = 0
}

BEGIN {
	FS = "-"
}

{
	succs[$1, ++nsuccs[$1]] = $2
	succs[$2, ++nsuccs[$2]] = $1
}

END {
	visit("start")
	print nways
}
