#!/usr/bin/awk -f

function visit(node, stop,    n, i) {
	if (node == "end")
		return 1
	if (visited[node] && (node == "start" || (node ~ /[a-z]/ && stop++)))
		return 0
	visited[node]++
	for (i = 1; i <= nsuccs[node]; i++)
		n += visit(succs[node, i], stop)
	visited[node]--
	return n
}

BEGIN {
	FS = "-"
}

{
	succs[$1, ++nsuccs[$1]] = $2
	succs[$2, ++nsuccs[$2]] = $1
}

END {
	print visit("start")
}
