#!/usr/bin/awk -f

function visit(node,    n, i) {
	if (!visited[node] && node == "end")
		return 1
	if (visited[node] && node ~ /[a-z]/)
		return 0
	visited[node] = 1
	for (i = 1; i <= nsuccs[node]; i++)
		n += visit(succs[node, i])
	visited[node] = 0
	return n
}

BEGIN {
	FS = "-"
}

{
	succs[$1, ++nsuccs[$1]] = $2
	succs[$2, ++nsuccs[$2]] = $1
}

END {
	print visit("start")
}
